<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Employee</name>
   <tag></tag>
   <elementGuidId>1f796d03-71c1-4db9-9059-49f541f619f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.ant-form-item-required</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='basic']/div/div/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>548f3290-b5b4-4128-aaa9-30df1bd76b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>basic_employee</value>
      <webElementGuid>bde0bd96-fe93-4875-9228-8ec334996847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-form-item-required</value>
      <webElementGuid>379f97f6-52e8-40db-bb9d-5e0e504f6c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Employee</value>
      <webElementGuid>fa299d7f-f450-4bd1-8ef2-f1630ffdf00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee</value>
      <webElementGuid>bb7b1f6a-7bb6-4f6c-8009-068010701e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic&quot;)/div[@class=&quot;ant-row css-e8tju&quot;]/div[@class=&quot;ant-col ant-col-sm-8 ant-col-md-8 ant-col-lg-8 css-e8tju&quot;]/div[@class=&quot;ant-form-item css-e8tju ant-form-item-has-success&quot;]/div[@class=&quot;ant-row ant-form-item-row css-e8tju&quot;]/div[@class=&quot;ant-col ant-form-item-label css-e8tju&quot;]/label[@class=&quot;ant-form-item-required&quot;]</value>
      <webElementGuid>4dd548b2-24c9-464c-b2aa-bbdbf6f3ba2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div/div/div/label</value>
      <webElementGuid>0d020938-b666-467c-9f17-6d38e4d0d781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Timesheet'])[3]/following::label[1]</value>
      <webElementGuid>2bd8764d-e5b1-4488-8df7-a01f20dac9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fateh Ali Khan'])[1]/following::label[1]</value>
      <webElementGuid>dc4b1f29-76e7-4ef6-8d2a-18ca3a513c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQR2023073100 - praveen ram'])[1]/preceding::label[1]</value>
      <webElementGuid>5bee74e3-6c8e-40cc-873e-ebafa6933f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work order'])[1]/preceding::label[1]</value>
      <webElementGuid>3c9e2662-276b-4ce6-9c09-3a393f1cfcee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>03dd0243-780f-4dfe-bac0-32bd0a470344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'Employee' and (text() = 'Employee' or . = 'Employee')]</value>
      <webElementGuid>70202db4-a240-45fd-ba6a-9ef6a5a14369</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
