<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reminder</name>
   <tag></tag>
   <elementGuidId>8cc5502e-fe06-45f0-8ef3-927a0b4b3bff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ant-page-header-heading-title.css-oxypi3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/section/div[2]/main/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c45a8fc8-bee5-409e-9036-3fb912448ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-page-header-heading-title css-oxypi3</value>
      <webElementGuid>403818b6-da03-487d-843f-63ebf5fa0036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Reminder</value>
      <webElementGuid>132babb4-6645-4c36-a667-ef810c81a76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reminder</value>
      <webElementGuid>1611138a-5701-4d61-a7d4-84eb18cfb22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;ant-pro css-oxypi3&quot;]/div[@class=&quot;css-oxypi3 ant-design-pro ant-pro-layout screen-lg ant-pro-layout-fix-siderbar ant-pro-layout-mix&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider css-e8tju&quot;]/div[@class=&quot;ant-pro-layout-container css-oxypi3&quot;]/main[@class=&quot;ant-layout-content ant-pro-layout-content css-oxypi3 ant-pro-layout-has-header ant-pro-layout-content-has-page-container&quot;]/div[@class=&quot;ant-pro-page-container css-oxypi3&quot;]/div[@class=&quot;ant-page-header css-oxypi3 ant-pro-page-container-warp-page-header css-oxypi3 ant-page-header-compact ant-page-header-ghost&quot;]/div[@class=&quot;ant-page-header-heading css-oxypi3&quot;]/div[@class=&quot;ant-page-header-heading-left css-oxypi3&quot;]/span[@class=&quot;ant-page-header-heading-title css-oxypi3&quot;]</value>
      <webElementGuid>49d9f32f-b676-4131-bbee-a3b9eb76430e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div[2]/main/div/div/div/div/span</value>
      <webElementGuid>17bd1b37-4d55-4c9c-a374-5f65cb003c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skill quotient'])[1]/following::span[1]</value>
      <webElementGuid>711ec9ae-08a6-4833-8413-68acce476057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQ'])[1]/following::span[2]</value>
      <webElementGuid>5dde632a-010d-44be-b827-a9a9f9c10110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From date - To date'])[1]/preceding::span[1]</value>
      <webElementGuid>0916f405-72f9-452f-aa5d-ecbd219b23a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/preceding::span[5]</value>
      <webElementGuid>aa10a67f-32d7-4cba-970e-070e8c6f408d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/span</value>
      <webElementGuid>bbd334d0-2aaf-469b-99ab-c4c71823564e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Reminder' and (text() = 'Reminder' or . = 'Reminder')]</value>
      <webElementGuid>d7988d53-260b-4edc-840a-f40776f66a89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
