<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Login_emailOrPhone</name>
   <tag></tag>
   <elementGuidId>c2de7787-1a70-470a-b97c-d5040deab137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailOrPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailOrPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43374964-eebf-4d5b-b84d-65b1ada33f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>ec480510-b588-4e0e-8a05-291105c4f3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailOrPhone</value>
      <webElementGuid>e1d27866-cc12-46a5-8740-0d4e61fc69ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg css-1n7nwfa</value>
      <webElementGuid>b7ebc965-42bd-45b7-be36-b4c56614287e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e79b4df7-ec18-4fe1-acd4-8db690f667cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailOrPhone&quot;)</value>
      <webElementGuid>62e7d853-62e9-4213-88e3-e76fedf56623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailOrPhone']</value>
      <webElementGuid>ae5267f4-9f30-420b-923c-2f7cc16c5151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/form/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>5ae5d7f5-bf73-48ec-829a-fd4976441fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>8a4f14ac-ac4c-4521-b149-2c81a6eaa1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email' and @id = 'emailOrPhone' and @type = 'text']</value>
      <webElementGuid>b22ada38-06cb-4358-b6cd-9c224802f3c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
