<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_basic_dob</name>
   <tag></tag>
   <elementGuidId>e122c579-9e7b-4a9d-9e94-17158d739c6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_dob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17350eb0-7e04-4453-9c62-06157ece5cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_dob</value>
      <webElementGuid>977a0270-58fd-405b-ae31-bcb02e616a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>1e0f4354-a202-49f6-a9bf-121699cb9d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>937f2470-2b45-4b85-9744-b587bfa8d226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>213294c3-a199-4f40-9b02-7fda35d6830c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_dob&quot;)</value>
      <webElementGuid>6a9547fd-36a2-4e13-9741-9a63dc57d323</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_dob']</value>
      <webElementGuid>d799ec4e-c32f-4266-9645-23c0c1058bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[3]/div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>4c74cf07-e7dc-4e33-afe1-e87c07052fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>e699f163-9c72-460e-aae8-a424f0daca6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_dob' and @placeholder = 'Date of Birth']</value>
      <webElementGuid>f5c4fd0c-6cbf-47ad-bfc4-e515bfcc9a48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
