<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Terms  Privacy Policy__afvz</name>
   <tag></tag>
   <elementGuidId>c67dbc89-0e18-4561-b803-03550c02c45a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='u_0_0_kV']/div/span[2]/a/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span._afw1 > a._9vcv > span._advp._aeam > img._afvz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8ff6c05d-87b3-43c2-bd1a-d4df96ebc4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_afvz</value>
      <webElementGuid>60a8cace-91ed-43b8-858b-a51357cf08d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>WhatsApp Main Page</value>
      <webElementGuid>72ad9347-51bd-496e-b411-88126990f05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.whatsapp.net/rsrc.php/v3/y7/r/DSxOAUB0raA.png</value>
      <webElementGuid>fa5c8552-9269-4d1f-bfb1-a869c79862c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_0_kV&quot;)/div[@class=&quot;_afvx&quot;]/span[@class=&quot;_afw1&quot;]/a[@class=&quot;_9vcv&quot;]/span[@class=&quot;_advp _aeam&quot;]/img[@class=&quot;_afvz&quot;]</value>
      <webElementGuid>d5cc46d5-43d6-4551-b769-fc8d401a1857</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='u_0_0_kV']/div/span[2]/a/span/img</value>
      <webElementGuid>fab2bd07-130d-4638-bca0-be4e6106f4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='WhatsApp Main Page'])[2]</value>
      <webElementGuid>f7cee8ef-9e44-419d-b73f-efa58464d9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a/span/img</value>
      <webElementGuid>98820eef-e0bb-499b-af39-b64e9f14ff52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'WhatsApp Main Page' and @src = 'https://static.whatsapp.net/rsrc.php/v3/y7/r/DSxOAUB0raA.png']</value>
      <webElementGuid>8cfcffaa-8703-4992-9b4d-597af12be6df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
