<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Login_emailOrPhone</name>
   <tag></tag>
   <elementGuidId>f5dd7029-6b1e-47e3-9b59-0063986d8a60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailOrPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailOrPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a2d6bf9-17c4-4314-b036-e1e6eb480efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>480c9039-9942-496a-b3b1-eee314e6d9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailOrPhone</value>
      <webElementGuid>c93e34f0-4958-49da-a732-3d3af79e0058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg css-1n7nwfa</value>
      <webElementGuid>4c60bbf1-59a2-427b-ac35-cd8aedc564fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41be7089-f0f8-4e26-a35b-5a6e00fad5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailOrPhone&quot;)</value>
      <webElementGuid>4c363e92-5bda-4c49-8027-d48393701ce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailOrPhone']</value>
      <webElementGuid>22bb55ef-649f-4a3b-af26-f204892fd097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/form/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>252eb3c4-7a40-48cf-8b93-cf482521bb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>9741cd27-be3c-4639-a504-9adca7fe8dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email' and @id = 'emailOrPhone' and @type = 'text']</value>
      <webElementGuid>911e654d-0658-40b5-9767-983bff9d83ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
