<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2772</name>
   <tag></tag>
   <elementGuidId>711f3d0d-36be-4729-b441-30d6d927c466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.total___ib27C > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/section/div[2]/main/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43a6ef05-7268-451b-b222-999c5756e70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2772</value>
      <webElementGuid>04074a7d-4303-45cc-b3d6-7b628d829cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;ant-pro css-oxypi3&quot;]/div[@class=&quot;css-oxypi3 ant-design-pro ant-pro-layout screen-lg ant-pro-layout-fix-siderbar ant-pro-layout-mix&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider css-e8tju&quot;]/div[@class=&quot;ant-pro-layout-container css-oxypi3&quot;]/main[@class=&quot;ant-layout-content ant-pro-layout-content css-oxypi3 ant-pro-layout-has-header ant-pro-layout-content-has-page-container&quot;]/div[@class=&quot;ant-pro-page-container css-oxypi3&quot;]/div[@class=&quot;ant-pro-grid-content css-oxypi3&quot;]/div[@class=&quot;ant-pro-grid-content-children css-oxypi3&quot;]/div[@class=&quot;ant-pro-page-container-children-content css-oxypi3&quot;]/div[@class=&quot;ant-row css-e8tju&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-sm-12 ant-col-md-12 ant-col-lg-12 ant-col-xl-6 css-e8tju&quot;]/div[@class=&quot;ant-card ant-card-bordered css-e8tju&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;chartCard___KcmBc&quot;]/div[@class=&quot;chartTop___c7aOD&quot;]/div[@class=&quot;metaWrap___XUrAH&quot;]/div[@class=&quot;total___ib27C&quot;]/a[1]</value>
      <webElementGuid>51d2c6d1-62b8-4e8c-a13f-e5c052cd1224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div[2]/main/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div[2]/a</value>
      <webElementGuid>73dd98df-7244-4af9-880a-fd7963bd83b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2772')]</value>
      <webElementGuid>fd504d52-7d21-48fc-b8e6-6f9bbb814e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Active)'])[1]/following::a[1]</value>
      <webElementGuid>ecadabd1-5fc6-42cc-a562-02d924306ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=': 20'])[1]/preceding::a[1]</value>
      <webElementGuid>0c515c45-86c6-4b11-ad4d-ad1d44d4b027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2772']/parent::*</value>
      <webElementGuid>4ae41fdf-0557-400b-b258-3a72ebfd3289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>9d9526e5-c55e-4472-a82e-5444c8b3d418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '2772' or . = '2772')]</value>
      <webElementGuid>9ba5a0a0-6595-461d-b654-626b92949edf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
