<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Login_emailOrPhone</name>
   <tag></tag>
   <elementGuidId>d0bbbb42-24af-49ca-9fa0-bde5c0d4e32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailOrPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailOrPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d2448f6-1305-4585-8e01-df4af4fc053c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>178bdb6f-4fe0-46a8-8e89-9f4908f77730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailOrPhone</value>
      <webElementGuid>e1a2b8ca-306b-4b51-bead-bea13d560ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg css-1n7nwfa</value>
      <webElementGuid>11ea95c1-e880-4595-8da1-d2bc59f6f20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cfa1f031-7de3-4edf-837b-fe19910bbea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailOrPhone&quot;)</value>
      <webElementGuid>0253fb29-c562-4dac-aff0-a4c2f2579c1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailOrPhone']</value>
      <webElementGuid>f9e8e29a-d450-408c-914d-b76324d01e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/form/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>3a841f27-86b3-436c-a95f-f21d50213eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>d531ca03-3482-4215-a652-7d2194591f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email' and @id = 'emailOrPhone' and @type = 'text']</value>
      <webElementGuid>c23feec9-8433-4df6-8319-e6c9f86535ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
