<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date From-To_basic_date</name>
   <tag></tag>
   <elementGuidId>a86813c1-851c-46a8-a0bb-0c9385afeb79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>586637f5-f63d-4454-b9c8-dea452f068ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_date</value>
      <webElementGuid>a6848dae-af9a-4362-9f0c-4d81cbc2a560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>From Date</value>
      <webElementGuid>b1967db6-bc7a-474f-9d91-fb7b78b19970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>ce6b4eeb-7405-41b4-a381-0d80e96d6bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>321a44e7-501d-4063-86d9-1ffdc9a8f513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_date&quot;)</value>
      <webElementGuid>eb14b664-165e-4196-b752-c4fda0711247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_date']</value>
      <webElementGuid>d872083e-3b94-4b63-8da1-c983e17d875e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[2]/div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>7e658ee2-604f-43de-a597-5bb7adc0af90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c8b4ab2f-158b-4a02-b6fc-b220681a5b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_date' and @placeholder = 'From Date']</value>
      <webElementGuid>d0cf0525-eead-4bd3-8511-68396b5e261c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
