<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work Hours_basic_workedHours</name>
   <tag></tag>
   <elementGuidId>8c1b2ea7-7543-4f29-afc2-69d9562ba7e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_workedHours</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_workedHours']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52dbbc53-d4c9-40f7-877b-128f03f61962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>309c3c46-fe70-4f79-b260-47e9dc1e9d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>8015b648-1071-42f6-a5bf-5fbde41a5cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a06a1ee-10e3-49a3-bf0e-6f2241f1437e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>df028b36-3e6f-4513-a399-f9fd4fbc8a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>805d323f-1250-4dca-9a03-4c419e71cc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter total work hour(s)</value>
      <webElementGuid>27a9f939-f908-4096-b8e0-7417b9abceed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_workedHours</value>
      <webElementGuid>b5488269-0437-4226-951d-21576ee15ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>4f21e343-96df-4161-84db-e6e607347149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec409e99-f81b-4f2e-b2db-5b8833490d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_workedHours&quot;)</value>
      <webElementGuid>02c54248-7766-4a7d-92ab-1db96b7ee886</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_workedHours']</value>
      <webElementGuid>9c0e9d85-7e0c-4407-9f37-444a34314838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[3]/div/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>0ec10e67-82db-4884-a895-e5d18d01c25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5f999be2-ef94-4448-859f-46434bc40783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Please enter total work hour(s)' and @id = 'basic_workedHours']</value>
      <webElementGuid>7f6420c8-34aa-49d6-b577-b2eb57a03694</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
