<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_3107</name>
   <tag></tag>
   <elementGuidId>260f783d-b5f9-45f4-9fc8-07f06ddd3d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ant-pro-select-item-option-content-light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = '3108' or . = '3108')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>47021935-5a8a-4bfc-9f72-f39a53723ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-pro-select-item-option-content-light</value>
      <webElementGuid>ce59f271-d91c-4e74-a201-17898dbd1209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3107</value>
      <webElementGuid>96fb6bdb-c867-44c8-bca6-52786952f5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3166&quot;)/div[@class=&quot;ant-select-item-option-content&quot;]/div[@class=&quot;ant-pro-select-item-option-content&quot;]/span[@class=&quot;ant-pro-select-item-option-content-light&quot;]</value>
      <webElementGuid>20f63eef-da9c-45a4-b230-cda02349fbaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3166']/div/div/span</value>
      <webElementGuid>c8f4b7ec-1885-4774-9b65-93b2d55c053b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select Employee'])[1]/following::span[7]</value>
      <webElementGuid>9144ce16-6d8e-4698-b45c-c6289380cb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3107']/parent::*</value>
      <webElementGuid>5c39f656-d94d-4a9e-a420-a2cd0d8517b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span</value>
      <webElementGuid>b09733c8-7c4c-441b-9fc9-f806bb03089f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '3107' or . = '3107')]</value>
      <webElementGuid>5da4c04f-d411-45af-b58c-09cceb729bcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
