<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Allocation Date_basic_allocationDate</name>
   <tag></tag>
   <elementGuidId>150d0519-cf46-444f-96f2-6cbfdf4220f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_allocationDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_allocationDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>595b00e1-0d1b-40ab-acfe-f0b45bb0f8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_allocationDate</value>
      <webElementGuid>75ead61b-115b-47c7-803b-b2bc7e3165d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Allocation Date</value>
      <webElementGuid>feaaa375-23cd-4c79-a31d-f0f250e735c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>8a85ac3d-9b6b-4113-b327-32c67b1fff50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>75237860-6107-447a-a89c-613eca28857b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_allocationDate&quot;)</value>
      <webElementGuid>5a962b15-39f5-4f6c-aaee-494bfc585bd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_allocationDate']</value>
      <webElementGuid>e72f5c61-1159-481a-98c6-d5fa364e7461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[3]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>08bb513d-6d66-4bf3-af1f-8d166ab5af8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>8779163e-f09b-4bec-8742-3920c7db794b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_allocationDate' and @placeholder = 'Allocation Date']</value>
      <webElementGuid>189dab8f-1edf-470d-9b91-c08627292f95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
