<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ma</name>
   <tag></tag>
   <elementGuidId>9d979f53-80d6-4a38-aa77-9a88df6db6f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_remarks</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='basic_remarks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2b569324-b4da-4f91-acbb-9a7737590276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>75f9d46c-6cfc-49e0-8139-15aedc211535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter remarks</value>
      <webElementGuid>80d037bd-8b49-4627-8148-f2948a7e9e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_remarks</value>
      <webElementGuid>a0b418cc-e42f-4233-994b-58a1664f52e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg ant-input-status-success css-e8tju</value>
      <webElementGuid>e8fa6639-1086-497e-88f8-0c7709fa801c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ma</value>
      <webElementGuid>a7107085-8735-440e-9d9d-4bf71f7906a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_remarks&quot;)</value>
      <webElementGuid>bae613c7-2150-49bf-81d2-519fe23e7570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='basic_remarks']</value>
      <webElementGuid>b9f8b7b0-c7e6-4994-976b-6109403c4058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[4]/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>b88d32f5-4294-4a09-aa35-056e310dcc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::textarea[1]</value>
      <webElementGuid>f60f4860-bf39-4a01-801a-044606801aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allocation Date'])[1]/following::textarea[1]</value>
      <webElementGuid>46d17e57-b3c7-45c7-9271-f2e055f743e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allocation Document'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e061d0d8-5197-4ab6-969f-618a9ffe8bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose File'])[1]/preceding::textarea[1]</value>
      <webElementGuid>0d84f58f-a1a2-4c72-9053-6cded2d8e708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ma']/parent::*</value>
      <webElementGuid>d0f48a82-5bac-4150-94e8-ad94967378c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9532a9e6-9ca7-41d5-8b70-f41dec02eb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Please enter remarks' and @id = 'basic_remarks' and (text() = 'ma' or . = 'ma')]</value>
      <webElementGuid>85349795-be5a-431e-ac44-66db4b9c6b51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
