<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submitted text</name>
   <tag></tag>
   <elementGuidId>d9986826-cd56-442c-b737-b20a64c5c022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.anticon.anticon-eye > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@class='ant-tag ant-tag-processing css-e8tju'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>86a8bc79-f223-4b7f-b92b-3060d04c12c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>64 64 896 896</value>
      <webElementGuid>54561285-61a8-4a8f-933f-6d0cf3b48c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>de9f98b4-9ca4-492b-ac0c-2141ac9b0c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>eye</value>
      <webElementGuid>13285e1e-84ac-4ec5-b6c2-96951d03e4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>859ccbcc-5bef-42bf-88a0-fd89a4ab4255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>5dbbd09c-d8d7-493f-9524-c01f23813019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>c3bce501-9784-4b9e-9410-77b3eef42630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f9de7739-b38f-420a-ad79-2ee3a1298d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;ant-pro css-3w3zlw&quot;]/div[@class=&quot;css-3w3zlw ant-design-pro ant-pro-layout screen-xl ant-pro-layout-fix-siderbar ant-pro-layout-mix&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider css-e8tju&quot;]/div[@class=&quot;ant-pro-layout-container css-3w3zlw&quot;]/main[@class=&quot;ant-layout-content ant-pro-layout-content css-3w3zlw ant-pro-layout-has-header ant-pro-layout-content-has-page-container&quot;]/div[@class=&quot;ant-pro-page-container css-3w3zlw&quot;]/div[@class=&quot;ant-pro-grid-content css-3w3zlw&quot;]/div[@class=&quot;ant-pro-grid-content-children css-3w3zlw&quot;]/div[@class=&quot;ant-pro-page-container-children-content css-3w3zlw&quot;]/div[@class=&quot;ant-pro-table css-3w3zlw&quot;]/div[@class=&quot;ant-pro-card css-3w3zlw&quot;]/div[@class=&quot;ant-pro-card-body css-3w3zlw&quot;]/div[@class=&quot;ant-table-wrapper css-e8tju&quot;]/div[@class=&quot;ant-spin-nested-loading css-e8tju&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table ant-table-middle ant-table-scroll-horizontal&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-content&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-cell-row-hover&quot;]/div[1]/button[@class=&quot;ant-btn css-e8tju ant-btn-link ant-btn-icon-only ant-tooltip-open&quot;]/span[@class=&quot;anticon anticon-eye&quot;]/svg[1]</value>
      <webElementGuid>05d9a801-b2df-44ea-9b90-648eae24808c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initiated'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>b85038e5-fc82-4586-a47b-e5d6b2fd12f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='submitted'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>80456409-5c94-4067-a6f4-a9da5a37c911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQT20230802615'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>24e46480-07cc-4cf3-aa58-285fc1979fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='praveen ram-SQR2023073100'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>c734196d-fcbf-4f54-98fb-1ababd646f63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
