<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RM</name>
   <tag></tag>
   <elementGuidId>65a11103-68dc-4648-af20-5acd6fa119d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ant-cascader-menu-item.ant-cascader-menu-item-active > div.ant-cascader-menu-item-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ff7f6ba-4490-46a2-89ee-333c4faa95d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-cascader-menu-item-content</value>
      <webElementGuid>7b3748a4-70e2-4b68-b6fc-884cf0072548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RM</value>
      <webElementGuid>17dbfd26-f06f-4f36-90bb-0d20a7683efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[5]/div[1]/div[@class=&quot;ant-select-dropdown ant-cascader-dropdown css-e8tju ant-select-dropdown-placement-bottomLeft&quot;]/div[1]/div[@class=&quot;ant-cascader-menus&quot;]/ul[@class=&quot;ant-cascader-menu&quot;]/li[@class=&quot;ant-cascader-menu-item ant-cascader-menu-item-active&quot;]/div[@class=&quot;ant-cascader-menu-item-content&quot;]</value>
      <webElementGuid>9912a077-6a76-4fc7-a1a1-b154c6891b1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[1]/following::div[1]</value>
      <webElementGuid>6c7c03ec-01d2-4cf2-acc6-96e66eef7741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INR'])[1]/following::div[2]</value>
      <webElementGuid>15572476-8e48-41ee-ae89-1ba3fca5b981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[3]/div</value>
      <webElementGuid>3e2a4ace-78c3-4a76-987a-01740808e88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'RM' or . = 'RM')]</value>
      <webElementGuid>16dc8b1f-b6f7-4ef9-ad3b-1103d0c114ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
