<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery Date_basic_deliveryDate</name>
   <tag></tag>
   <elementGuidId>4e907bce-e8ae-45e2-9072-53736e481dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_deliveryDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#basic_deliveryDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03c5a3b3-f46b-42bb-8b1f-cf0b45702f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_deliveryDate</value>
      <webElementGuid>5d9fd5c2-c462-4edf-ac99-bad5e0bf33bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Delivery Date</value>
      <webElementGuid>a79fd80c-9af2-442e-9e39-b52afba7410b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>f720ce3d-ce62-4483-9951-86fa7891891a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a19ad71d-a0e4-4ef6-a3df-1e2976c42edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_deliveryDate&quot;)</value>
      <webElementGuid>843ea4f8-8b84-4a19-9bc4-e9b89ae985a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_deliveryDate']</value>
      <webElementGuid>d30f3c9a-2617-47e7-b156-93cce5582605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[7]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>34ac80c4-8b83-4a3c-9146-af3a41e68933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>8b5c6da1-8dae-478d-94f1-56db748f1a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_deliveryDate' and @placeholder = 'Delivery Date']</value>
      <webElementGuid>7712975e-f2b2-4133-91c2-aec2560723cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
