<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Warranty Expiry Date_basic_warrantyEx_b40fbd</name>
   <tag></tag>
   <elementGuidId>911b1956-35bf-412b-809e-9de5bcfa2b3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_warrantyExpiryDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#basic_warrantyExpiryDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b62adaa-f4e2-47d1-9796-8098cb2fd70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_warrantyExpiryDate</value>
      <webElementGuid>b14b8e34-22f7-4b56-8e0a-679d9e08cdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Warranty Expiry Date</value>
      <webElementGuid>ad9bec41-72d1-48b7-886c-cc5242e4d21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>f40dd74d-57f0-434a-8790-de6078bcd1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9a50c1b3-c449-4006-b479-7598f1bf5e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_warrantyExpiryDate&quot;)</value>
      <webElementGuid>ad2d9bf8-4123-474f-af16-f8fba2008739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_warrantyExpiryDate']</value>
      <webElementGuid>ac7dd67d-dd59-4f2c-953f-ce88cb8555ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[7]/div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>082aee5f-fd77-49c7-ab69-af54b6b20596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>d951d604-e341-4cb6-9f08-0a65f6c76dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_warrantyExpiryDate' and @placeholder = 'Warranty Expiry Date']</value>
      <webElementGuid>3b01f12f-355c-4a13-b64c-3c2535b684ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
