<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Purchase Order_basic_purchaseOrderNo</name>
   <tag></tag>
   <elementGuidId>7ca1ec82-94ab-47bb-9ce8-7450a2c30b74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_purchaseOrderNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#basic_purchaseOrderNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d11b449a-959d-4f1f-9623-4e513a572cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Purchase Order</value>
      <webElementGuid>79135a3f-3d60-4cd0-b568-a658c7e32103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_purchaseOrderNo</value>
      <webElementGuid>5232f2d3-b6f8-4f46-9f89-f8bbfc743e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a4af9a53-f5f6-48fd-93f0-289a64c4edb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg css-e8tju</value>
      <webElementGuid>045424b2-104e-4dc8-9887-708ec6b079c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8674d735-4267-42ec-9e1c-b879b859f0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_purchaseOrderNo&quot;)</value>
      <webElementGuid>09fdeff0-7d27-403b-89be-43ff33128f2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_purchaseOrderNo']</value>
      <webElementGuid>b6f12844-13ff-4736-995a-0e33b365d394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[6]/div/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>5f9a062b-4461-46fd-97cd-c22589cdb74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>98b16395-dca0-4a9a-9d76-311017b51d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Purchase Order' and @id = 'basic_purchaseOrderNo' and @type = 'text']</value>
      <webElementGuid>94cbf42b-8272-4645-afce-d126129bdf9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
