<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payment Method_basic_paymentMethod</name>
   <tag></tag>
   <elementGuidId>a988c542-8a71-4ea1-8e78-30a4b4df2cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_paymentMethod']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#basic_paymentMethod</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8185363-59a6-48a9-83d5-552024e475a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Payment Method</value>
      <webElementGuid>54282a4e-894d-4e35-84ef-b85cf306b952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_paymentMethod</value>
      <webElementGuid>806d39c8-a136-41d3-83b4-0e4e53bb4088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3ea12b45-d78d-45e1-b29d-0830aed91c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg css-e8tju</value>
      <webElementGuid>9e9cbd4d-7631-4123-896e-31417683b269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42dc4f20-a3b5-4af1-b3ae-6e0604917071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_paymentMethod&quot;)</value>
      <webElementGuid>dbc9864e-7074-4104-93e1-66b106b1c86b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_paymentMethod']</value>
      <webElementGuid>e485ae3f-9300-4705-88cb-083a120218e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[6]/div[2]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>68f336ef-deb8-46c6-8d6a-884c94bbf432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>86d893bf-e944-42fd-a40b-3b81ccbe1db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Payment Method' and @id = 'basic_paymentMethod' and @type = 'text']</value>
      <webElementGuid>1738f2f7-32a2-42fc-aab6-f5ef0e13d01f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
