<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Purchase Date_basic_purchaseDate</name>
   <tag></tag>
   <elementGuidId>b2b8783b-7ef7-463a-b78e-6fbbf3e621f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_purchaseDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#basic_purchaseDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5f5ebeb-d66a-4d95-9dd0-b1352b8fee52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_purchaseDate</value>
      <webElementGuid>760b74f3-58f0-4ecc-bb05-25ee53438c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Purchase Date</value>
      <webElementGuid>0e15d1f9-d16e-4ba8-a113-a78ebfb60903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>19ab1cc4-d204-4a4d-a95c-181d74d7a177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3a515d2f-0b21-4a36-b32e-34727041b98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_purchaseDate&quot;)</value>
      <webElementGuid>547eada2-2453-4366-b999-15c4a4fd851c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_purchaseDate']</value>
      <webElementGuid>04a9cf5f-ac5d-42ca-9184-6f2a23be84e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[5]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>733cde85-2759-4ae1-b1e0-646f351a0329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>19d3e910-3058-47a6-87de-bed23eb26c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_purchaseDate' and @placeholder = 'Purchase Date']</value>
      <webElementGuid>59d5e66e-1cd9-4cdb-857f-0ce8801dce2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
