<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Estimated Life_basic_estimatedLife</name>
   <tag></tag>
   <elementGuidId>d3490f10-569c-4cc7-b045-c3bdcb1eac2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_estimatedLife']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#basic_estimatedLife</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef5de5a9-ffad-4e26-a6bd-d428a1e9891c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b36b60c6-ec0e-4403-98e7-392c84ccac9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>b95fe689-40be-4496-ab17-fd95382117f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8faa4633-6d61-4029-8ed6-891a301ef206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2f35dbbb-c0d3-48b4-9d2c-df6a4e36ffe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Estimated Life</value>
      <webElementGuid>ff0ed138-4a43-4bc6-8538-3a8b4bdcec53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_estimatedLife</value>
      <webElementGuid>f94dd645-de43-487a-8f37-dcc5f3a29666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>d8ea8af0-0a39-417d-889e-10315e0bae97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_estimatedLife&quot;)</value>
      <webElementGuid>20054a27-57da-4a2a-adc8-67bf3aa344e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_estimatedLife']</value>
      <webElementGuid>fb8eb68d-b229-40a9-87ef-c982ea3ef0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[8]/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>0c3968e7-53e0-4166-96f1-610219959c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>bae5ea01-41cb-49b0-aca3-2029db3f6109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Estimated Life' and @id = 'basic_estimatedLife']</value>
      <webElementGuid>0ff3c816-6a21-4bab-b7db-f75d2139543f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
