<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_RM</name>
   <tag></tag>
   <elementGuidId>815db22d-23d9-441c-a657-158a053ee9f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='basic']/div/div/div[5]/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-select.ant-cascader.css-e8tju.ant-select-single.ant-select-allow-clear.ant-select-show-arrow.ant-select-open > div.ant-select-selector > span.ant-select-selection-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c518ed5a-2183-4ec0-a8f3-e13321f5394b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-item</value>
      <webElementGuid>b6f30564-d2cc-45a5-bea5-1c6abe1dbf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>RM</value>
      <webElementGuid>a665697d-7030-46ee-9f0d-e0d782c9946b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RM</value>
      <webElementGuid>9f4df270-1325-4552-b362-8592a0095479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic&quot;)/div[@class=&quot;ant-row css-e8tju&quot;]/div[@class=&quot;ant-col ant-col-sm-24 ant-col-md-24 ant-col-lg-12 css-e8tju&quot;]/div[@class=&quot;ant-row css-e8tju&quot;]/div[@class=&quot;ant-col ant-col-sm-24 ant-col-md-12 ant-col-lg-12 css-e8tju&quot;]/div[@class=&quot;ant-form-item css-e8tju ant-form-item-has-success&quot;]/div[@class=&quot;ant-row ant-form-item-row css-e8tju&quot;]/div[@class=&quot;ant-col ant-form-item-control css-e8tju&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;ant-input-number-group-wrapper ant-input-number-group-wrapper-lg ant-input-number-group-wrapper-status-success css-e8tju&quot;]/div[@class=&quot;ant-input-number-wrapper ant-input-number-group css-e8tju&quot;]/div[@class=&quot;ant-input-number-group-addon&quot;]/div[@class=&quot;ant-select ant-cascader css-e8tju ant-select-single ant-select-allow-clear ant-select-show-arrow ant-select-open&quot;]/div[@class=&quot;ant-select-selector&quot;]/span[@class=&quot;ant-select-selection-item&quot;]</value>
      <webElementGuid>7ca370c3-a3cb-410f-93c7-740126f415e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[5]/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/div/span[2]</value>
      <webElementGuid>aeb4551f-7922-4d2e-aa96-ab6309305d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Value'])[1]/following::span[6]</value>
      <webElementGuid>42d7255c-24ea-4d90-909d-077074357196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Date'])[1]/following::span[10]</value>
      <webElementGuid>64f76250-acbe-4e8f-9774-64d5053aa16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Order'])[1]/preceding::span[5]</value>
      <webElementGuid>a38f7afd-6df8-40a8-8ed9-abbc2b2804f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/preceding::span[9]</value>
      <webElementGuid>0dee7b74-b10c-44d3-b964-2fb68ddfc60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RM']/parent::*</value>
      <webElementGuid>998abd7d-aeac-4fa6-bfb9-d081f9647da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span[2]</value>
      <webElementGuid>e137a5dd-8159-4bb6-9ef8-4b384a39cf88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'RM' and (text() = 'RM' or . = 'RM')]</value>
      <webElementGuid>84577a17-2bc8-466f-a97d-0b85579d6d69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
