<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Re</name>
   <tag></tag>
   <elementGuidId>d842cd0e-3baa-48d0-93c8-cd89cc10e71e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='basic_assetDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#basic_assetDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f3ff4621-078e-4af2-b632-f2dbed7d61c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7c37c55e-7504-4fed-8fef-bcacc5b60d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter asset description</value>
      <webElementGuid>79e6dec9-578e-446d-914d-31aa1208b296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_assetDescription</value>
      <webElementGuid>4dcdbbf9-f3d5-449f-bc93-d4459f83d96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg ant-input-status-success css-e8tju</value>
      <webElementGuid>495b82e2-2b99-4b7a-a491-fccf8907e792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Re</value>
      <webElementGuid>c3c4d9a9-a4ae-46a8-be80-d57f1c13e490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_assetDescription&quot;)</value>
      <webElementGuid>06bfbb10-841f-47d2-81a1-3b13cbe7b6bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='basic_assetDescription']</value>
      <webElementGuid>0aaf2f4c-6562-4c6b-9af8-27948d5d3d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[4]/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>97f6d8c1-2bcc-4da2-8acb-cca923f3ce9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Description'])[1]/following::textarea[1]</value>
      <webElementGuid>8303a3cd-6aad-4195-8152-33c2ccfad99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptop'])[1]/following::textarea[1]</value>
      <webElementGuid>3fba2533-6b43-4ddb-8efa-8bef0a2bbe80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Date'])[1]/preceding::textarea[1]</value>
      <webElementGuid>dedb66d3-c190-4d82-91c9-77d136029e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Value'])[1]/preceding::textarea[1]</value>
      <webElementGuid>86c8fc47-ec16-42cf-bb15-0a2ecb7ad906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Re']/parent::*</value>
      <webElementGuid>92a4b94f-9098-4940-900e-ed1123fd86dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b752d619-825d-48a5-bcd7-adb7af52893b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Please enter asset description' and @id = 'basic_assetDescription' and (text() = 'Re' or . = 'Re')]</value>
      <webElementGuid>658f3312-77b8-4b9a-b010-79b7c67c0a7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
