<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_R</name>
   <tag></tag>
   <elementGuidId>f4e54329-66f0-4c4c-9c20-845218201c43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='basic_assetDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#basic_assetDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c49341e3-33b3-4747-a4e1-9a41eb05a591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>0ce6f1d0-f143-4504-892e-8af4e0e85ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter asset description</value>
      <webElementGuid>17ad3fc9-1657-4353-8f0e-e3859b2365f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_assetDescription</value>
      <webElementGuid>952090e5-5eb7-4adf-9cb3-7bf5acfa38e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg ant-input-status-success css-e8tju</value>
      <webElementGuid>4119994a-78e7-4b6c-ba76-10151acaf750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>R</value>
      <webElementGuid>e622dfa9-ed9a-43db-b563-959e9f018b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_assetDescription&quot;)</value>
      <webElementGuid>fb48509f-a8e5-45c9-a227-836f1f831417</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='basic_assetDescription']</value>
      <webElementGuid>5b0213f2-b6f5-4ca6-ab24-ff5e1c055853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[4]/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>f45333fb-f3f6-4108-9c01-42e562d72942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Description'])[1]/following::textarea[1]</value>
      <webElementGuid>58a08503-cb69-440a-bdfb-40bf7a6371bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptop'])[1]/following::textarea[1]</value>
      <webElementGuid>b99e9963-6416-4ad7-9ea4-ca39748358b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Date'])[1]/preceding::textarea[1]</value>
      <webElementGuid>c463cf24-7ea0-4478-a9f1-a191d728bf6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Value'])[1]/preceding::textarea[1]</value>
      <webElementGuid>2bdca0b5-99cb-47d7-94a2-b501d49f3ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='R']/parent::*</value>
      <webElementGuid>4a363801-1b6a-45ab-a2ff-ed78030e6819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f5ec209e-cc01-4745-bbf0-b0233569973c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Please enter asset description' and @id = 'basic_assetDescription' and (text() = 'R' or . = 'R')]</value>
      <webElementGuid>557f9bbd-38ca-415c-88c6-9ff93e9fd498</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
