<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Country</name>
   <tag></tag>
   <elementGuidId>21cdcd02-bd0e-491a-ab99-9fcd85026799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_dateOfJoining</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input [@id='basic_nationality_list_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9c0659b-f55e-4985-9fb4-7cfdc8d89938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_dateOfJoining</value>
      <webElementGuid>703fd34f-2e49-4106-af8e-af14744b6400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Joining</value>
      <webElementGuid>3f1a0500-8211-4d88-8f30-e54496f67ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>951fc1ba-dfbd-4755-986c-704ecedfb1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8917bd84-0366-41ef-a902-03b8d72f5cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_dateOfJoining&quot;)</value>
      <webElementGuid>05d226c3-e926-4ff1-bc05-52c60d0824e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_dateOfJoining']</value>
      <webElementGuid>f9072d6f-664c-48e4-bfa0-faf2e4ecb2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[5]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>da02fcaf-3d89-484b-8672-ac2f1f26e284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>0ee8c166-ab9e-467e-8ff7-3a6f3b595476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_dateOfJoining' and @placeholder = 'Date of Joining']</value>
      <webElementGuid>7c19e1b5-b6f5-4c35-97a6-81a86884fec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
