<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date of Birth</name>
   <tag></tag>
   <elementGuidId>135891d1-f938-4fd4-9a40-f643e162270f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_dateOfJoining</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input [@id='basic_dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fd60b9a-3073-4892-88bf-d5415414fe3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_dateOfJoining</value>
      <webElementGuid>3b5acc1d-2976-4776-b17c-873a8c4a39f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Joining</value>
      <webElementGuid>864af675-2390-4a22-bb1e-20026cb15f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>6c89e840-e972-4e7f-90cf-4e7b9c6e4a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>52c19bb9-f1bd-4d6f-929b-567931a81fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_dateOfJoining&quot;)</value>
      <webElementGuid>3bfe2898-619a-4f7e-9dee-91119e592a68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_dateOfJoining']</value>
      <webElementGuid>eef582bc-c0ae-49b9-96df-de2c360b38a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[5]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>77e8fa03-0258-4e9c-abde-59d170f3f0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>0c4cb5e6-5936-4489-8988-e11ec210181f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_dateOfJoining' and @placeholder = 'Date of Joining']</value>
      <webElementGuid>8322fc2c-c400-4888-8e03-f1b4471fc8bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
