<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_basic_firstName</name>
   <tag></tag>
   <elementGuidId>db3326c1-4626-4536-a3b8-1fdda30c46fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_firstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>000a6144-43a4-45b6-b02a-a79ab5ba16fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>b9e355d1-7bda-44f2-a999-36f8c66d8d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_firstName</value>
      <webElementGuid>84a21fc2-830a-4b1d-b432-d2c4472f0f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e5ecefa6-2353-4d5c-8583-1df0d534475d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-e8tju</value>
      <webElementGuid>f9a2cd85-e3ec-4ea8-8e6a-b81233066990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1c647bf-e891-460d-9be8-2477b6a475d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>R</value>
      <webElementGuid>752937b5-3548-47e9-b127-60a9543acb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_firstName&quot;)</value>
      <webElementGuid>0e8242ab-5429-4a74-86a4-cc75959d41ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_firstName']</value>
      <webElementGuid>b7d9cf6c-f7f4-4ffb-95cf-962d5f72d005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div[2]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>19a3b693-b5d0-4924-b4ec-1f098bd6f7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>eb78e70e-a847-48cc-a327-6fdd18171141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'First Name' and @id = 'basic_firstName' and @type = 'text']</value>
      <webElementGuid>1e3f3135-e983-43f7-aeb6-563496efe637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
