<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary Email_basic_email</name>
   <tag></tag>
   <elementGuidId>e2864998-fb2a-4274-9b22-3b3ee8f183f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bdf1615-16d1-45e2-976d-c8cb535dd057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Primary Email</value>
      <webElementGuid>f741c42d-1473-4354-b59a-ccaba3c95fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_email</value>
      <webElementGuid>7271090c-b121-41b5-8563-fd7fca94ae74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>260</value>
      <webElementGuid>7f859f25-7276-44e7-b16c-a87f96aa6bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-e8tju</value>
      <webElementGuid>00a82c80-58e7-4f05-9e89-94b320f58653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eac9a67c-a04e-40c4-8b77-5a1247199ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_email&quot;)</value>
      <webElementGuid>68c10329-6847-4e96-a939-aec9bcc335e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_email']</value>
      <webElementGuid>eefe2579-70fd-4cea-a3f4-96d7eccc6687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div[4]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>a7f31604-0475-455c-95d7-285175c7e4dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>46d1dc26-ee1f-43a8-b624-62e47f4be4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Primary Email' and @id = 'basic_email' and @type = 'text']</value>
      <webElementGuid>cb35191d-e5fd-4de5-8767-15542c9f2dfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
