<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Joining_basic_dateOfJoining</name>
   <tag></tag>
   <elementGuidId>689c9426-ca07-4981-b910-b3385d30fa4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_dateOfJoining</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_dateOfJoining']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a36fe853-ac9f-4a73-a0be-09971cd43a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_dateOfJoining</value>
      <webElementGuid>b3993245-742d-4f73-83c0-51e6ea0ac57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Joining</value>
      <webElementGuid>f72d207b-35fb-4465-801c-5ba45b026362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>3f0f309e-67a8-4a6b-9aa2-eb66dbf71af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>baae72f5-c6ed-4833-b00f-ce68475887b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_dateOfJoining&quot;)</value>
      <webElementGuid>df0ee578-97ad-4362-8f76-21a661a8c999</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_dateOfJoining']</value>
      <webElementGuid>4fffec7a-bb0b-4275-9afa-0a11be0df129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[5]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>45bf5c25-ac9c-42cb-adc8-2e3010554dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a9c219a9-3d9a-40dc-88a3-d4f92194076c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_dateOfJoining' and @placeholder = 'Date of Joining']</value>
      <webElementGuid>1ae6e7c5-c3b0-4f5c-a45b-1b9f5082446b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
