<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Current Location_basic_currentLocation</name>
   <tag></tag>
   <elementGuidId>fe091ba2-022b-4122-ab85-68727d6077d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_currentLocation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_currentLocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c8d9324-40d0-4fa6-8fcb-a12c8165d8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ad2b8275-3a56-4aaa-a13a-6c61631f92b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_currentLocation</value>
      <webElementGuid>917fae52-5829-46f5-9ae8-6498c4901547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2d0c2a66-5994-4117-b241-93ccf3e5b874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-search-input</value>
      <webElementGuid>62e1c312-c2ff-4808-b908-fb2b298980ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>32b85f27-f17b-4645-9f78-e15181a49492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>26ad83b6-6ea5-44bb-8e76-eba1eb507dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>basic_currentLocation_list</value>
      <webElementGuid>f05af54e-7469-48d7-b493-9940e25abba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>c184d20a-9eb6-4001-942f-4be32257e57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>basic_currentLocation_list</value>
      <webElementGuid>78ce56f1-33e5-49ff-b976-97ce1d4d29cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>basic_currentLocation_list_0</value>
      <webElementGuid>c021c1f2-9bd6-4e9d-91a7-888ea6464ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>m</value>
      <webElementGuid>a54eaead-9d52-4a0b-98dc-7bfe34edc128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8341b6f5-0a8b-4fc6-add3-2a1ed5843e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_currentLocation&quot;)</value>
      <webElementGuid>ba7152cd-4e68-43b9-95e2-5a69e2b146a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_currentLocation']</value>
      <webElementGuid>d768dbc3-5b94-4c6d-8209-1a85c9466a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[4]/div/div/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>4ac10b64-e104-4d20-9fc2-614f63c51bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>77ef33c9-e4ac-42ec-b5d9-1d2a56046e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'basic_currentLocation']</value>
      <webElementGuid>203422cf-a46a-4378-8dc3-4edef2c69260</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
