<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_basic_phone</name>
   <tag></tag>
   <elementGuidId>3687fedc-1a4c-448c-ba98-dd7c7d06caf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60f6b5b0-3aa5-47d2-9a23-aab91bb89ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>0dfe2d2f-929f-499f-b8fd-29711d7531c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_phone</value>
      <webElementGuid>cf52db24-344b-449e-94bb-ecbe9cc2bf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>e8158cd7-ca5a-4792-9a26-a7e9bb3700a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-e8tju</value>
      <webElementGuid>81efa981-610b-428a-abb0-c7f653e8bb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a4f8303-0c2c-44d3-9565-fb8f684da557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_phone&quot;)</value>
      <webElementGuid>d0c37d4c-e6b3-402a-9edb-d3743ea36664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_phone']</value>
      <webElementGuid>c8ad1976-2fec-43e4-a5da-85549693f0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div[5]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>87660548-5421-4424-ac9a-2be8ffef9284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>f8fd8ea9-a4c1-4ed8-80be-e80712233fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Phone Number' and @id = 'basic_phone' and @type = 'text']</value>
      <webElementGuid>54eb6910-e548-48f8-8f62-f19782476d4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
