<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_basic_lastName</name>
   <tag></tag>
   <elementGuidId>244ee44f-e867-428a-b984-784e41669a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_lastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea140d0d-22c4-4021-885b-12988bb169d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>53655b21-c2fd-43c3-af08-15afe340f738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_lastName</value>
      <webElementGuid>15b16cdd-bad8-4803-aad7-9de4c7d14a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8320ec3b-0104-486b-bc37-b0d7b3786686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-e8tju</value>
      <webElementGuid>92eb7fa4-1df7-40d3-9c54-1470fa860fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41742528-67cf-497d-8c65-11f5063a14c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>k</value>
      <webElementGuid>d5ecc721-f3b2-4b4b-a620-a8f50d9e2ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_lastName&quot;)</value>
      <webElementGuid>cf90245f-b729-4057-824a-729f5478302c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_lastName']</value>
      <webElementGuid>f1c3957b-2e52-4904-8f76-3438d3da36e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div[3]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>a8722ae0-a008-4edd-aa56-43b5b4ab20e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>149d3b85-c563-46be-a11e-f440542ed81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Last Name' and @id = 'basic_lastName' and @type = 'text']</value>
      <webElementGuid>b75fa466-907c-47af-90cf-ad95d9382123</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
