<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>article_SQA2023090059</name>
   <tag></tag>
   <elementGuidId>11df1c6a-784c-41a0-9708-31d3be52b1fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>article.ant-typography.css-e8tju</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-tabs-1-panel-1']/div/div[2]/div/div[2]/div/div/div/div/div/table/tbody/tr[2]/td/article</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>article</value>
      <webElementGuid>d5e0c7a6-ca57-454c-9b9c-b2984c1c30e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-typography css-e8tju</value>
      <webElementGuid>f757a749-cf4d-4f22-9008-033a453fd6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SQA2023090059</value>
      <webElementGuid>0691a86f-94d5-4adf-bcde-99eadde8579d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-1-panel-1&quot;)/div[@class=&quot;ant-pro-table css-oxypi3&quot;]/div[@class=&quot;ant-pro-card css-oxypi3&quot;]/div[@class=&quot;ant-pro-card-body css-oxypi3&quot;]/div[@class=&quot;ant-table-wrapper css-e8tju&quot;]/div[@class=&quot;ant-spin-nested-loading css-e8tju&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table ant-table-middle ant-table-scroll-horizontal&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-content&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-cell-row-hover&quot;]/article[@class=&quot;ant-typography css-e8tju&quot;]</value>
      <webElementGuid>16f9607c-0fe8-4dfc-91cb-5fdd0fa30861</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-1-panel-1']/div/div[2]/div/div[2]/div/div/div/div/div/table/tbody/tr[2]/td/article</value>
      <webElementGuid>6072f22f-19d4-46f3-a26f-529a04dc9243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[1]/following::article[1]</value>
      <webElementGuid>620bbea1-df4a-4fef-8fc8-3bc224d189b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[3]/following::article[1]</value>
      <webElementGuid>493d4036-b3d1-40e9-82bd-2a47b31dcb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='macbook'])[1]/preceding::article[1]</value>
      <webElementGuid>e9c8ff4f-fdd5-47c4-92be-a1a9c1e549fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptop'])[1]/preceding::article[2]</value>
      <webElementGuid>6cea0432-d655-4c33-a1a6-0393726712d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SQA2023090059']/parent::*</value>
      <webElementGuid>4c425adc-140f-4dc9-8c6a-e06f90af1644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article</value>
      <webElementGuid>9305e18c-2c53-4972-a65b-00264ee95a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//article[(text() = 'SQA2023090059' or . = 'SQA2023090059')]</value>
      <webElementGuid>518c9411-c9bb-43e7-b3e3-2e6db6c83e1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
