<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Role</name>
   <tag></tag>
   <elementGuidId>bd2f2e00-39a1-4c6b-a3fd-c9295e6e56df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[title=&quot;Role&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/section/div[2]/main/div/div[2]/div/div/div/div/form/div/div/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a9defce3-c4d6-4cee-950c-cc41fb167d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>filter.roles.id</value>
      <webElementGuid>15292139-b753-456d-8d37-9a17f6db1b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>e13fb471-7a06-4774-af99-c77668487b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>a01ce6b5-4f3c-42d9-87ec-b301e9621314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;ant-pro css-oxypi3&quot;]/div[@class=&quot;css-oxypi3 ant-design-pro ant-pro-layout screen-lg ant-pro-layout-fix-siderbar ant-pro-layout-mix&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider css-e8tju&quot;]/div[@class=&quot;ant-pro-layout-container css-oxypi3&quot;]/main[@class=&quot;ant-layout-content ant-pro-layout-content css-oxypi3 ant-pro-layout-has-header ant-pro-layout-content-has-page-container&quot;]/div[@class=&quot;ant-pro-page-container css-oxypi3&quot;]/div[@class=&quot;ant-pro-grid-content css-oxypi3&quot;]/div[@class=&quot;ant-pro-grid-content-children css-oxypi3&quot;]/div[@class=&quot;ant-pro-page-container-children-content css-oxypi3&quot;]/div[@class=&quot;ant-pro-table css-oxypi3&quot;]/div[@class=&quot;css-oxypi3 ant-pro-card ant-pro-table-search ant-pro-table-search-query-filter&quot;]/form[@class=&quot;ant-form ant-form-vertical css-e8tju ant-pro-query-filter css-oxypi3 ant-pro-form css-oxypi3&quot;]/div[@class=&quot;ant-row ant-row-start ant-pro-query-filter-row css-oxypi3 css-e8tju&quot;]/div[@class=&quot;ant-col ant-col-12 css-e8tju&quot;]/div[@class=&quot;ant-form-item css-e8tju&quot;]/div[@class=&quot;ant-row ant-form-item-row css-e8tju&quot;]/div[@class=&quot;ant-col ant-form-item-label css-e8tju&quot;]/label[1]</value>
      <webElementGuid>a1c4c6bd-cedd-4a42-85fa-c5f410c782ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div[2]/main/div/div[2]/div/div/div/div/form/div/div/div/div/div/label</value>
      <webElementGuid>763a45df-8047-4735-94df-ae7e65aee5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[3]/following::label[1]</value>
      <webElementGuid>260c5f9d-2e32-4910-a23a-223bcd7c45f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fateh Ali Khan'])[1]/following::label[1]</value>
      <webElementGuid>d69f6a6a-f457-4bc9-88cf-1411252c17af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Role'])[1]/preceding::label[1]</value>
      <webElementGuid>e7c43e2d-1050-4f75-971e-0fd800990595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::label[1]</value>
      <webElementGuid>dfc0c77a-cd73-4c42-8371-70cea4618700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Role']/parent::*</value>
      <webElementGuid>3e382dc7-b7ab-41c2-a965-0fb36793e311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>b9ebd23d-c1ad-4ad9-916e-23cb5dfeb4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'Role' and (text() = 'Role' or . = 'Role')]</value>
      <webElementGuid>ab0538ba-6b78-423f-8469-a86059a0251a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
