<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date From-To_basic_date</name>
   <tag></tag>
   <elementGuidId>f03c0ddc-7367-4020-95ed-3d2711206a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>147d52b2-3527-4fb0-aef2-0bdb24e6c6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_date</value>
      <webElementGuid>48e0dc73-a757-4a24-a577-1f5d71d1415e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>From Date</value>
      <webElementGuid>eea60c1c-0029-438f-b65d-857e228cc9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>5702c922-1cba-4e7b-adf9-52118fab98e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9aaa827-ccb5-4e85-8d66-9afc930c60ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_date&quot;)</value>
      <webElementGuid>d3290be8-dbe3-4a1a-96d4-74adce49b1b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_date']</value>
      <webElementGuid>a5ae356b-0d28-45ea-b722-a910d268584e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[2]/div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>c60dd742-d926-4a2a-8ab1-6eb9a27eec35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>e761c455-a017-4850-b150-903a80f61770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_date' and @placeholder = 'From Date']</value>
      <webElementGuid>1300e308-1fd9-40ad-886f-40c5da6056fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
