<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_646</name>
   <tag></tag>
   <elementGuidId>74273103-90bb-4532-9569-6780447cedfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ant-pro-select-item-option-content-light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='2692']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd92fe6b-65b1-41f2-94ee-b91ec503e121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-pro-select-item-option-content-light</value>
      <webElementGuid>e986714b-8117-4be3-8190-4f7cdd90b614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>646</value>
      <webElementGuid>9372543c-5286-451c-a5e0-b7efc50ef790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2692&quot;)/div[@class=&quot;ant-select-item-option-content&quot;]/div[@class=&quot;ant-pro-select-item-option-content&quot;]/span[@class=&quot;ant-pro-select-item-option-content-light&quot;]</value>
      <webElementGuid>5d0345bb-41a1-4330-b931-2d17c0345420</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2692']/div/div/span</value>
      <webElementGuid>fcb9bef3-dc4d-4f0e-8bda-9e49f657f97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select Employee'])[1]/following::span[7]</value>
      <webElementGuid>3b38566a-0ce4-4ccd-8b7c-d350fc2685e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='646']/parent::*</value>
      <webElementGuid>b3b81e46-d250-4a29-b257-b9b66ae9bcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span</value>
      <webElementGuid>5d6a894d-6776-4507-ac9a-4786110160bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '646' or . = '646')]</value>
      <webElementGuid>f817faa9-6806-4183-840c-eab8f045363c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
